name: Deploy to Codeberg Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: docker
    container: gradle:8.12-jdk21

    steps:
      - uses: actions/checkout@v4

      - name: Build production
        run: gradle jsBrowserProductionWebpack

      - name: Copy static assets
        run: cp src/jsMain/resources/index.html src/jsMain/resources/styles.css build/kotlin-webpack/js/productionExecutable/

      - name: Deploy to Codeberg Pages
        uses: https://codeberg.org/git-pages/action@v2
        with:
          site: "https://${{ forge.repository_owner }}.codeberg.page/Scoreo/"
          token: ${{ forge.token }}
          source: build/kotlin-webpack/js/productionExecutable/
