import {
  AlertTriangle,
  ArrowLeft,
  BarChart3,
  Calendar,
  CheckCircle2,
  Cloud,
  Crown,
  Eye,
  Flame,
  Gamepad2,
  History,
  Home,
  Languages,
  Loader2,
  Medal,
  Menu,
  Merge,
  Minus,
  Mountain,
  Palette,
  Pencil,
  Play,
  Plus,
  Skull,
  Sparkles,
  Star,
  Swords,
  Target,
  Trash2,
  TrendingUp,
  Trophy,
  Upload,
  WifiOff,
  X,
  XCircle,
  type LucideIcon,
} from 'lucide-react'

/**
 * The closed icon set. The app names an icon, it never imports a glyph: adding
 * one is a design-system change, so the set stays one stroke family (Lucide,
 * 24×24, stroke 2).
 */
export const ICONS = {
  alert: AlertTriangle,
  back: ArrowLeft,
  calendar: Calendar,
  check: CheckCircle2,
  close: X,
  cloud: Cloud,
  crown: Crown,
  delete: Trash2,
  edit: Pencil,
  error: XCircle,
  flame: Flame,
  games: Gamepad2,
  history: History,
  home: Home,
  language: Languages,
  loader: Loader2,
  medal: Medal,
  menu: Menu,
  merge: Merge,
  minus: Minus,
  mountain: Mountain,
  offline: WifiOff,
  palette: Palette,
  play: Play,
  plus: Plus,
  skull: Skull,
  sparkles: Sparkles,
  star: Star,
  stats: BarChart3,
  swords: Swords,
  target: Target,
  trendingUp: TrendingUp,
  trophy: Trophy,
  upload: Upload,
  view: Eye,
} satisfies Record<string, LucideIcon>

export type IconName = keyof typeof ICONS
export const ICON_NAMES = Object.keys(ICONS) as IconName[]
